---
groups:
  - admin:
    users:
      - email: admin@example.com
        first_name: Zack
        last_name: Yo
    scopes: []
  - developer:
    users:
      - email: developer@example.com
        first_name: Nik
        last_name: Nilson
    scopes: []
  - support:
    users:
      - email: support@example.com
        first_name: Vladimir
        last_name: Nikolaev
    scopes: []

## All scopes:
# [
#   "alerts.create",
#   "alerts.read",
#   "alerts.update",
#   "alerts.delete",
#   "asm.groups.create",
#   "asm.groups.read",
#   "asm.groups.update",
#   "asm.groups.delete",
#   "asm.groups.suppressions.create",
#   "asm.groups.suppressions.read",
#   "asm.groups.suppressions.update",
#   "asm.groups.suppressions.delete",
#   "asm.suppressions.global.create",
#   "asm.suppressions.global.read",
#   "asm.suppressions.global.update",
#   "asm.suppressions.global.delete",
#   "billing.create",
#   "billing.read",
#   "billing.update",
#   "billing.delete",
#   "ui.confirm_email",
#   "signup.trigger_confirmation",
#   "ui.provision",
#   "ips.warmup.create",
#   "ips.warmup.read",
#   "ips.warmup.update",
#   "ips.warmup.delete",
#   "ips.pools.create",
#   "ips.pools.read",
#   "ips.pools.update",
#   "ips.pools.delete",
#   "ips.pools.ips.create",
#   "ips.pools.ips.read",
#   "ips.pools.ips.update",
#   "ips.pools.ips.delete",
#   "ips.assigned.read",
#   "ips.create",
#   "ips.read",
#   "ips.update",
#   "ips.delete",
#   "mail.send",
#   "mail_settings.read",
#   "mail_settings.bcc.create",
#   "mail_settings.bcc.read",
#   "mail_settings.bcc.update",
#   "mail_settings.bcc.delete",
#   "mail_settings.address_whitelist.create",
#   "mail_settings.address_whitelist.read",
#   "mail_settings.address_whitelist.update",
#   "mail_settings.address_whitelist.delete",
#   "mail_settings.footer.create",
#   "mail_settings.footer.read",
#   "mail_settings.footer.update",
#   "mail_settings.footer.delete",
#   "mail_settings.forward_spam.create",
#   "mail_settings.forward_spam.read",
#   "mail_settings.forward_spam.update",
#   "mail_settings.forward_spam.delete",
#   "mail_settings.plain_content.create",
#   "mail_settings.plain_content.read",
#   "mail_settings.plain_content.update",
#   "mail_settings.plain_content.delete",
#   "mail_settings.spam_check.create",
#   "mail_settings.spam_check.read",
#   "mail_settings.spam_check.update",
#   "mail_settings.spam_check.delete",
#   "mail_settings.bounce_purge.create",
#   "mail_settings.bounce_purge.read",
#   "mail_settings.bounce_purge.update",
#   "mail_settings.bounce_purge.delete",
#   "mail_settings.forward_bounce.create",
#   "mail_settings.forward_bounce.read",
#   "mail_settings.forward_bounce.update",
#   "mail_settings.forward_bounce.delete",
#   "partner_settings.read",
#   "partner_settings.new_relic.create",
#   "partner_settings.new_relic.read",
#   "partner_settings.new_relic.update",
#   "partner_settings.new_relic.delete",
#   "partner_settings.sendwithus.create",
#   "partner_settings.sendwithus.read",
#   "partner_settings.sendwithus.update",
#   "partner_settings.sendwithus.delete",
#   "tracking_settings.read",
#   "tracking_settings.click.create",
#   "tracking_settings.click.read",
#   "tracking_settings.click.update",
#   "tracking_settings.click.delete",
#   "tracking_settings.subscription.create",
#   "tracking_settings.subscription.read",
#   "tracking_settings.subscription.update",
#   "tracking_settings.subscription.delete",
#   "tracking_settings.open.create",
#   "tracking_settings.open.read",
#   "tracking_settings.open.update",
#   "tracking_settings.open.delete",
#   "tracking_settings.google_analytics.create",
#   "tracking_settings.google_analytics.read",
#   "tracking_settings.google_analytics.update",
#   "tracking_settings.google_analytics.delete",
#   "user.webhooks.event.settings.create",
#   "user.webhooks.event.settings.read",
#   "user.webhooks.event.settings.update",
#   "user.webhooks.event.settings.delete",
#   "user.webhooks.event.test.create",
#   "user.webhooks.event.test.read",
#   "user.webhooks.event.test.update",
#   "user.webhooks.event.test.delete",
#   "user.webhooks.parse.settings.create",
#   "user.webhooks.parse.settings.read",
#   "user.webhooks.parse.settings.update",
#   "user.webhooks.parse.settings.delete",
#   "stats.read",
#   "stats.global.read",
#   "categories.stats.read",
#   "categories.stats.sums.read",
#   "devices.stats.read",
#   "clients.stats.read",
#   "clients.phone.stats.read",
#   "clients.tablet.stats.read",
#   "clients.webmail.stats.read",
#   "clients.desktop.stats.read",
#   "geo.stats.read",
#   "mailbox_providers.stats.read",
#   "browsers.stats.read",
#   "subusers.stats.read",
#   "subusers.stats.sums.read",
#   "subusers.stats.monthly.read",
#   "user.webhooks.parse.stats.read",
#   "subusers.create",
#   "subusers.read",
#   "subusers.update",
#   "subusers.delete",
#   "subusers.monitor.create",
#   "subusers.monitor.read",
#   "subusers.monitor.update",
#   "subusers.monitor.delete",
#   "subusers.credits.create",
#   "subusers.credits.read",
#   "subusers.credits.update",
#   "subusers.credits.delete",
#   "subusers.credits.remaining.create",
#   "subusers.credits.remaining.read",
#   "subusers.credits.remaining.update",
#   "subusers.credits.remaining.delete",
#   "subusers.reputations.read",
#   "subusers.summary.read",
#   "suppression.bounces.create",
#   "suppression.bounces.read",
#   "suppression.bounces.update",
#   "suppression.bounces.delete",
#   "suppression.blocks.create",
#   "suppression.blocks.read",
#   "suppression.blocks.update",
#   "suppression.blocks.delete",
#   "suppression.invalid_emails.create",
#   "suppression.invalid_emails.read",
#   "suppression.invalid_emails.update",
#   "suppression.invalid_emails.delete",
#   "suppression.spam_reports.create",
#   "suppression.spam_reports.read",
#   "suppression.spam_reports.update",
#   "suppression.spam_reports.delete",
#   "suppression.unsubscribes.create",
#   "suppression.unsubscribes.read",
#   "suppression.unsubscribes.update",
#   "suppression.unsubscribes.delete",
#   "templates.create",
#   "templates.read",
#   "templates.update",
#   "templates.delete",
#   "templates.versions.create",
#   "templates.versions.read",
#   "templates.versions.update",
#   "templates.versions.delete",
#   "templates.versions.activate.create",
#   "templates.versions.activate.read",
#   "templates.versions.activate.update",
#   "templates.versions.activate.delete",
#   "user.account.read",
#   "user.credits.read",
#   "user.email.read",
#   "user.profile.create",
#   "user.profile.read",
#   "user.profile.update",
#   "user.profile.delete",
#   "user.timezone.create",
#   "user.timezone.read",
#   "user.timezone.update",
#   "user.timezone.delete",
#   "user.username.read",
#   "user.settings.enforced_tls.read",
#   "user.settings.enforced_tls.update",
#   "api_keys.create",
#   "api_keys.read",
#   "api_keys.update",
#   "api_keys.delete",
#   "credentials.create",
#   "credentials.read",
#   "credentials.update",
#   "credentials.delete",
#   "categories.create",
#   "categories.read",
#   "categories.update",
#   "categories.delete",
#   "mail_settings.template.create",
#   "mail_settings.template.read",
#   "mail_settings.template.update",
#   "mail_settings.template.delete",
#   "newsletter.create",
#   "newsletter.read",
#   "newsletter.update",
#   "newsletter.delete",
#   "marketing_campaigns.create",
#   "marketing_campaigns.read",
#   "marketing_campaigns.update",
#   "marketing_campaigns.delete",
#   "ui.signup_complete",
#   "mail.batch.create",
#   "mail.batch.read",
#   "mail.batch.update",
#   "mail.batch.delete",
#   "user.scheduled_sends.create",
#   "user.scheduled_sends.read",
#   "user.scheduled_sends.update",
#   "user.scheduled_sends.delete",
#   "access_settings.whitelist.create",
#   "access_settings.whitelist.read",
#   "access_settings.whitelist.update",
#   "access_settings.whitelist.delete",
#   "access_settings.activity.read",
#   "whitelabel.create",
#   "whitelabel.read",
#   "whitelabel.update",
#   "whitelabel.delete",
#   "suppression.create",
#   "suppression.read",
#   "suppression.update",
#   "suppression.delete",
#   "teammates.create",
#   "teammates.read",
#   "teammates.update",
#   "teammates.delete",
#   "messages.read",
#   "validations.email.read",
#   "validations.email.create",
#   "marketing.read",
#   "marketing.automation.read",
#   "design_library.read",
#   "design_library.create",
#   "design_library.update",
#   "design_library.delete",
#   "email_testing.read",
#   "email_testing.write",
#   "sender_verification_eligible",
#   "sso.settings.create",
#   "sso.settings.read",
#   "sso.settings.update",
#   "sso.settings.delete",
#   "sender_verification_legacy",
#   "sso.teammates.create",
#   "sso.teammates.update",
#   "2fa_required"
# ]
